const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],D=window.CREOVA_DATA,img=D.img;
const defaults={view:"home",start:"Marl",target:"",radius:1000,tripType:"Urlaub",weatherPref:"Sonnig",budget:2000,persons:2,dateStart:"",dateEnd:"",interests:["Meer","Radfahren","Camping","gutes Essen"],selected:[],packDone:{},customPack:[],houseDone:{},alarm:{arrival:"10:00",drive:"5 h 30 min",buffer:"30 min",wakeLead:"60 min",departure:"04:00",wake:"03:00"}};
let state=load(),seed=0;
const suggestions=D.destinations.map(x=>({id:x[0],title:x[1],loc:x[2],km:x[3],price:x[4],rating:x[5],weather:x[6],img:img[x[7]],tags:x[8].split(","),desc:x[9],timeline:x[10].split("|")}));
const pack=D.pack.map((x,i)=>{let [name,cat,tags,key]=x.split("|");return{id:"p"+i,name,cat,tags:tags.split(","),img:img[key],qty:"1 / 1"}});
function load(){try{return {...defaults,...JSON.parse(localStorage.creova_ultimate_v4||"{}")}}catch(e){return {...defaults}}}
function save(){localStorage.creova_ultimate_v4=JSON.stringify(state)}
function money(n){return Number(n||0).toLocaleString("de-DE")+" €"}
function toast(m){let t=document.createElement("div");t.className="toast";t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function selected(){return suggestions.filter(s=>state.selected.includes(s.id))}
function score(s){let v=s.tags.filter(t=>state.interests.includes(t)).length*18;if(s.tags.includes(state.tripType))v+=28;if(s.km<=state.radius)v+=12;if(s.weather===state.weatherPref||state.weatherPref==="Egal")v+=15;if(state.target&&`${s.title} ${s.loc} ${s.tags.join(" ")}`.toLowerCase().includes(state.target.toLowerCase()))v+=30;v+=(s.title.length+seed*11)%17;return v}
function nav(view){if(view==="planen")view="timeline";state.view=view;save();$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$$(".view").forEach(v=>v.classList.toggle("hidden",v.id!==`view-${view}`));render();scrollTo({top:0,behavior:"smooth"})}
function render(){renderHome();renderBudget();renderResults();renderPlan();renderPack();renderHouse();renderDepart();renderGallery();renderTimeline();renderMap();renderExport();}
function renderHome(){if(!$("#start"))return;$("#tripType").innerHTML=D.tripTypes.map(x=>`<option>${x}</option>`).join("");["start","target","dateStart","dateEnd","weatherPref"].forEach(id=>{let e=$("#"+id);if(e)e.value=state[id]});$("#radius").value=state.radius;$("#tripType").value=state.tripType;$("#budgetInput").value=state.budget;$("#persons").value=state.persons;$("#chips").innerHTML=D.interests.map(([n,i])=>`<button class="chip ${state.interests.includes(n)?"active":""}" data-chip="${n}"><span>${i}</span>${n}</button>`).join("");$$("[data-chip]").forEach(c=>c.onclick=()=>{let n=c.dataset.chip;state.interests=state.interests.includes(n)?state.interests.filter(x=>x!==n):[...state.interests,n];save();render();});}
function renderBudget(){let sum=selected().reduce((a,b)=>a+b.price,0),rest=state.budget-sum,pp=state.persons?sum/state.persons:sum;["budgetInput","budgetInput2"].forEach(id=>{let e=$("#"+id);if(e&&document.activeElement!==e)e.value=state.budget});["persons","persons2"].forEach(id=>{let e=$("#"+id);if(e&&document.activeElement!==e)e.value=state.persons});["budgetTiles","budgetTiles2"].forEach(id=>{let e=$("#"+id);if(e)e.innerHTML=`<div class="tile"><span>Budget</span><b>${money(state.budget)}</b></div><div class="tile"><span>Ausgewählt</span><b>${money(sum)}</b></div><div class="tile"><span>Rest</span><b>${money(rest)}</b></div><div class="tile"><span>pro Person</span><b>${money(pp)}</b></div>`});$("#stickyCount").textContent=state.selected.length+" Vorschläge ausgewählt";$("#stickySum").textContent=money(sum);if($("#budgetList"))$("#budgetList").innerHTML=selected().map(s=>`<div class="row"><div>💶</div><div><b>${s.title}</b><br><span class="muted">${s.km} km · ${s.tags.slice(0,3).join(", ")}</span></div><b>${money(s.price)}</b></div>`).join("")||'<p class="muted">Noch keine Kosten ausgewählt.</p>'}
function sortedSuggestions(){let arr=[...suggestions].sort((a,b)=>score(b)-score(a));let sort=$("#sort")?.value;if(sort==="Preis niedrig")arr.sort((a,b)=>a.price-b.price);if(sort==="Entfernung")arr.sort((a,b)=>a.km-b.km);if(sort==="Wetter passend")arr.sort((a,b)=>(b.weather===state.weatherPref)-(a.weather===state.weatherPref));if(sort==="Bewertung")arr.sort((a,b)=>b.rating-a.rating);return arr}
function renderResults(){let e=$("#results");if(!e)return;e.innerHTML=sortedSuggestions().map(s=>`<article class="suggest ${state.selected.includes(s.id)?"selected":""}" data-sug="${s.id}"><div class="photo" style="background-image:url('${s.img}')"></div><div class="match">${score(s)}% Match</div><div class="check">✓</div><div class="body"><h3>${s.title}</h3><p class="muted">${s.desc}</p><div class="tags">${s.tags.slice(0,5).map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="meta"><span>⭐ ${s.rating}</span><span>${s.km} km</span><b>${money(s.price)}</b></div><button class="detailBtn" data-detail="${s.id}">Details anzeigen</button></div></article>`).join("");$$("[data-sug]").forEach(c=>c.onclick=e=>{if(e.target.closest("[data-detail]"))return;toggleSug(c.dataset.sug)});$$("[data-detail]").forEach(b=>b.onclick=e=>{e.stopPropagation();showDetail(b.dataset.detail)})}
function toggleSug(id){state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id];save();render();toast("Auswahl aktualisiert")}
function showDetail(id){let s=suggestions.find(x=>x.id===id),mini=[["Restaurants",img.food,"Passende Restaurants und Cafés"],["Campingplätze",img.camp,"Stellplätze, Dachzelt und Sanitär"],["Aktivitäten",s.img,"Touren, Erlebnisse, Familie"],["Unterkünfte",img.tent,"Hotels, Apartments, Ferienhäuser"]];$("#detailContent").innerHTML=`<div class="detailView"><div class="detailImg" style="background-image:url('${s.img}')"></div><div class="detailPanel"><h2>${s.title}</h2><p class="muted">${s.desc}</p><div class="tags">${s.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="budgetGrid"><div class="tile"><span>Match</span><b>${score(s)}%</b></div><div class="tile"><span>Entfernung</span><b>${s.km} km</b></div><div class="tile"><span>Kosten</span><b>${money(s.price)}</b></div><div class="tile"><span>Wetter</span><b>${s.weather}</b></div></div><button class="btn primary" style="margin-top:14px" onclick="toggleSug('${s.id}')">${state.selected.includes(s.id)?"Entfernen":"Übernehmen"}</button><button class="btn" style="margin-top:8px" onclick="openMaps('${encodeURIComponent(s.loc)}')">Karte öffnen</button></div></div><h2 style="margin-top:22px">Dazugehörige Vorschläge</h2><div class="miniGrid">${mini.map(m=>`<div class="infoMini"><img src="${m[1]}"><div><h3>${m[0]}</h3><p class="muted">${m[2]}</p><button class="btn" onclick="toggleSug('${s.id}')">für Planung übernehmen</button></div></div>`).join("")}</div>`;nav("details")}
function openMaps(q){window.open("https://www.google.com/maps/search/?api=1&query="+q,"_blank")}
function renderPlan(){renderTimeline()}
function relevantPack(){let active=[...state.interests,state.tripType,...selected().flatMap(s=>s.tags)];return pack.filter(p=>p.tags.includes("all")||p.tags.some(t=>active.includes(t))).concat(state.customPack.map((x,i)=>({id:"custom"+i,cat:"Eigene",name:x,img:img.bag,tags:["all"],qty:"1 / 1"})))}
function renderPack(){let area=$("#products");if(!area)return;let all=relevantPack(),cats=[...new Set(all.map(i=>i.cat))],filter=$("#packFilter")?.value||"Alle Kategorien";$("#packFilter").innerHTML='<option>Alle Kategorien</option>'+cats.map(c=>`<option>${c}</option>`).join("");$("#packFilter").value=filter;if(filter!=="Alle Kategorien")all=all.filter(i=>i.cat===filter);let done=relevantPack().filter(i=>state.packDone[i.id]).length,total=relevantPack().length;$("#packText").textContent=`${done} / ${total}`;$("#packFill").style.width=(total?done/total*100:0)+"%";$("#packCats").innerHTML=cats.map(c=>{let l=relevantPack().filter(i=>i.cat===c),d=l.filter(i=>state.packDone[i.id]).length;return `<div class="packCat"><h3>${c}</h3><div class="bar"><div class="fill" style="width:${l.length?d/l.length*100:0}%"></div></div><p class="muted">${d} / ${l.length}</p></div>`}).join("");area.innerHTML=all.map(p=>`<article class="product ${state.packDone[p.id]?"done":""}" data-pack="${p.id}"><div class="photo" style="background-image:url('${p.img}')"></div><div class="check">✓</div><div class="body"><h3>${p.name}</h3><p class="muted">${p.cat} · ${p.qty}</p></div></article>`).join("");$$("[data-pack]").forEach(p=>p.onclick=()=>{state.packDone[p.dataset.pack]=!state.packDone[p.dataset.pack];save();renderPack()})}
function renderHouse(){let e=$("#houseList");if(!e)return;e.innerHTML=D.house.map(([id,t,i])=>`<div class="row ${state.houseDone[id]?"done":""}" data-house="${id}"><div class="box">✓</div><div class="text"><b>${t}</b></div><div>${i}</div></div>`).join("");$$("[data-house]").forEach(r=>r.onclick=()=>{state.houseDone[r.dataset.house]=!state.houseDone[r.dataset.house];save();renderHouse()})}
function parseTime(t){let m=String(t).match(/(\d{1,2}):(\d{2})/);return m?+m[1]*60+ +m[2]:600}function parseMins(t){let h=(String(t).match(/(\d+)\s*h/)||[])[1]||0;let m=(String(t).match(/(\d+)\s*min/)||[])[1]||0;return +h*60+ +m}function fmt(min){min=(min%1440+1440)%1440;return String(Math.floor(min/60)).padStart(2,"0")+":"+String(min%60).padStart(2,"0")}
function renderDepart(){if(!$("#arrival"))return;["arrival","drive","buffer","wakeLead"].forEach(id=>{$("#"+id).value=state.alarm[id]});let dep=parseTime(state.alarm.arrival)-parseMins(state.alarm.drive)-parseMins(state.alarm.buffer),wake=dep-parseMins(state.alarm.wakeLead);state.alarm.departure=fmt(dep);state.alarm.wake=fmt(wake);$("#depTime").textContent=state.alarm.departure;$("#wakeTime").textContent=state.alarm.wake}
function renderGallery(){let e=$("#gallery");if(!e)return;[img.hero,img.lake,img.tent,img.mount,img.camp,img.beach,img.bike,img.spa,img.city,img.kid,img.food,img.tech].forEach(x=>e.innerHTML+=`<img src="${x}">`)}
function renderTimeline(){let e=$("#timelineFull");if(!e)return;let sel=selected();e.innerHTML=sel.length?`<div class="timeline">${sel.flatMap((s,idx)=>s.timeline.map((t,i)=>`<div class="tl"><div><h3>Tag ${idx+i+1}: ${t}</h3><p class="muted">${s.title}</p><button class="btn" onclick="toast('Verschieben vorbereitet')">verschieben</button></div><img src="${s.img}"></div>`)).join("")}</div>`:`<p class="muted">Noch keine Timeline.</p>`}
function renderMap(){let e=$("#mapList");if(!e)return;e.innerHTML=sortedSuggestions().map(s=>`<article class="suggest"><div class="photo" style="background-image:url('${s.img}')"></div><div class="body"><h3>${s.title}</h3><p class="muted">${s.loc}</p><button class="btn primary" onclick="openMaps('${encodeURIComponent(s.loc)}')">Karte öffnen</button></div></article>`).join("")}
function makeExport(){let sel=selected(),lines=["CREOVA Reiseplan","","Startort: "+state.start,"Ziel/Region: "+state.target,"Zeitraum: "+(state.dateStart||"-")+" bis "+(state.dateEnd||"-"),"Budget: "+money(state.budget),"Personen: "+state.persons,"Interessen: "+state.interests.join(", "),"","Auswahl:"];sel.forEach(s=>lines.push("- "+s.title+" | "+money(s.price)+" | "+s.km+" km"));lines.push("","Offene Packliste:");relevantPack().filter(p=>!state.packDone[p.id]).slice(0,100).forEach(p=>lines.push("- "+p.name+" ("+p.cat+")"));lines.push("","Hauscheck offen:");D.house.filter(h=>!state.houseDone[h[0]]).forEach(h=>lines.push("- "+h[1]));return lines.join("\n")}
function renderExport(){let e=$("#exportText");if(e)e.value=makeExport()}
function bind(){$$("[data-view]").forEach(b=>b.onclick=()=>nav(b.dataset.view));$("#tripType").innerHTML=D.tripTypes.map(x=>`<option>${x}</option>`).join("");["start","target","dateStart","dateEnd","weatherPref"].forEach(id=>{let e=$("#"+id);if(e)e.oninput=ev=>{state[id]=ev.target.value;save();render()}});$("#radius").onchange=e=>{state.radius=+e.target.value;save();render()};$("#tripType").onchange=e=>{state.tripType=e.target.value;save();render()};$("#budgetInput").oninput=e=>{state.budget=+e.target.value||0;save();renderBudget()};$("#budgetInput2").oninput=e=>{state.budget=+e.target.value||0;save();renderBudget()};$("#persons").oninput=e=>{state.persons=+e.target.value||1;save();renderBudget()};$("#persons2").oninput=e=>{state.persons=+e.target.value||1;save();renderBudget()};$("#sort").onchange=renderResults;$("#btnRefresh").onclick=()=>{seed++;renderResults();toast("Vorschläge neu sortiert")};$("#btnClear").onclick=()=>{state.selected=[];state.interests=[];save();render();toast("Auswahl geleert")};$("#addInterest").onclick=()=>{let v=$("#customInterest").value.trim();if(v&&!state.interests.includes(v)){state.interests.push(v);$("#customInterest").value="";save();render()}};$("#addPack").onclick=()=>{let v=$("#customPack").value.trim();if(v){state.customPack.push(v);$("#customPack").value="";save();renderPack()}};$("#packFilter").onchange=renderPack;$("#btnLocation").onclick=()=>{navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>$("#loc").textContent=`✅ Standort: ${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`,()=>toast("Standort nicht freigegeben")):toast("Standort nicht verfügbar")};$("#saveAlarm").onclick=()=>{["arrival","drive","buffer","wakeLead"].forEach(id=>state.alarm[id]=$("#"+id).value);save();renderDepart();toast("Wecker gespeichert")};$("#rebalanceTimeline").onclick=()=>toast("Timeline neu verteilt");$("#downloadPlan").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([makeExport()],{type:"text/plain"}));a.download="creova-reiseplan.txt";a.click()};$("#resetAll").onclick=()=>{if(confirm("Alles löschen?")){localStorage.removeItem("creova_ultimate_v4");location.reload()}};$("#resetApp").onclick=()=>{if(confirm("App zurücksetzen?")){localStorage.removeItem("creova_ultimate_v4");location.reload()}}}
document.addEventListener("DOMContentLoaded",()=>{bind();nav(state.view||"home")});