
const $=(q,r=document)=>r.querySelector(q);
const $$=(q,r=document)=>[...r.querySelectorAll(q)];
const DATA=window.CREOVA_DATA;

const state={view:"ziel",selected:[],selectedPoi:[],packDone:{},pois:[],weather:null,coords:null,locationName:"",budget:0,persons:1,interests:[],car:{consumption:7.2,fuelPrice:1.75,distanceKm:0}};
let map=null,markers=[];

function money(v){return Number(v||0).toLocaleString("de-DE")+" €";}
function toast(t){const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200);}
function nav(v){state.view=v;$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$$(".view").forEach(s=>s.classList.toggle("hidden",s.id!=="view-"+v));render();if(v==="karte")setTimeout(initMap,120);if(v==="wetter"&&!state.weather)setTimeout(loadWeather,120);scrollTo({top:0,behavior:"smooth"});}
function chosen(){return [...DATA.suggestions.filter(s=>state.selected.includes(s.id)),...state.pois.filter(p=>state.selectedPoi.includes(p.id))];}
function itemPrice(i){return i.price||({restaurant:35,camping:45,hotel:110}[i.kind]||30);}
function fuelCost(){return Math.round(state.car.distanceKm*state.car.consumption/100*state.car.fuelPrice);}
function totalCost(){return chosen().reduce((s,i)=>s+itemPrice(i),0)+fuelCost();}

function render(){renderChips();renderSuggestions();renderDiscover();renderPois();renderBudget();renderPack();renderPlan();renderTimeline();renderHouse();renderTours();renderWeatherPanel();renderExport();renderMapMarkers();$("#selCount").textContent=chosen().length+" Vorschläge ausgewählt";$("#sum").textContent=money(totalCost());$("#bTotal").textContent=money(state.budget);$("#bUsed").textContent=money(chosen().reduce((s,i)=>s+itemPrice(i),0));$("#bCar").textContent=money(fuelCost());$("#bRest").textContent=money(state.budget-totalCost());}
function renderChips(){const base=["Meer","Camping","Dachzelt","Radfahren","Wandern","Natur","Wellness","Kinder","Essen","Stadt"];$("#chips").innerHTML=base.map(c=>`<button class="chip ${state.interests.includes(c)?"active":""}" data-chip="${c}">${c}</button>`).join("");$$("[data-chip]").forEach(b=>b.onclick=()=>{let c=b.dataset.chip;state.interests=state.interests.includes(c)?state.interests.filter(x=>x!==c):[...state.interests,c];render();});}
function card(i,type="suggestion"){let sel=type==="poi"?state.selectedPoi.includes(i.id):state.selected.includes(i.id);return `<article class="cardItem ${sel?"selected":""}" data-${type}="${i.id}"><img src="${i.img}" alt=""><div class="selectDot">✓</div><div class="cardBody"><h3>${i.title||i.name}</h3><p>${i.desc||i.address||"Live-Ort aus OpenStreetMap"}</p><div>${(i.tags||[i.kind]).map(t=>`<span class="tag">${t}</span>`).join("")}</div><p><b>${money(itemPrice(i))}</b></p></div></article>`;}
function sortedSuggestions(){return [...DATA.suggestions].sort((a,b)=>b.tags.filter(t=>state.interests.includes(t)).length-a.tags.filter(t=>state.interests.includes(t)).length);}
function renderSuggestions(){const e=$("#results");if(!e)return;e.innerHTML=sortedSuggestions().map(i=>card(i)).join("");$$("[data-suggestion]").forEach(c=>c.onclick=()=>{let id=c.dataset.suggestion;state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id];render();});}
function renderDiscover(){const e=$("#discoverCards");if(e)e.innerHTML=sortedSuggestions().map(i=>card(i)).join("");}
function renderPois(){const e=$("#poiList");if(!e)return;let f=$("#poiFilter").value,map={Restaurants:"restaurant",Camping:"camping",Hotels:"hotel"};let arr=state.pois.filter(p=>f==="Alle"||p.kind===map[f]);e.innerHTML=arr.length?arr.map(i=>card(i,"poi")).join(""):"<p>Noch keine Live-Orte geladen. Nutze „Live-Daten laden“.</p>";$$("[data-poi]").forEach(c=>c.onclick=()=>{let id=c.dataset.poi;state.selectedPoi=state.selectedPoi.includes(id)?state.selectedPoi.filter(x=>x!==id):[...state.selectedPoi,id];render();});}

async function geocode(q){const r=await fetch("https://nominatim.openstreetmap.org/search?format=json&limit=1&q="+encodeURIComponent(q));const j=await r.json();if(!j[0])throw new Error("Ort nicht gefunden");return{lat:+j[0].lat,lon:+j[0].lon,name:j[0].display_name};}
async function loadLiveData(){try{$("#status").textContent="Live-Daten werden geladen ...";let q=$("#destination").value.trim()||$("#start").value.trim()||"Marl Deutschland";let g=await geocode(q);state.coords={lat:g.lat,lon:g.lon};state.locationName=g.name;await Promise.all([loadWeather(),loadPois()]);$("#status").textContent="Live-Daten geladen: "+g.name;toast("Live-Daten geladen");render();}catch(e){$("#status").textContent="Fehler: "+e.message;toast("Live-Daten nicht erreichbar");}}
async function useGps(){try{$("#status").textContent="GPS wird abgefragt ...";const p=await new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:7000}):rej(new Error("GPS nicht verfügbar")));state.coords={lat:p.coords.latitude,lon:p.coords.longitude};state.locationName="Aktueller Standort";await Promise.all([loadWeather(),loadPois()]);$("#status").textContent="GPS übernommen";render();}catch(e){state.coords={lat:51.647,lon:7.096};state.locationName="Fallback Marl";await Promise.all([loadWeather(),loadPois()]);render();}}
async function loadWeather(){if(!state.coords){state.coords={lat:51.647,lon:7.096};state.locationName="Fallback Marl";}let{lat,lon}=state.coords;let u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`;let r=await fetch(u,{cache:"no-store"});state.weather=await r.json();renderWeatherPanel();renderTopWeather();}
function renderTopWeather(){if(!state.weather?.current)return;$("#topWeather").innerHTML=`<span>📍 ${state.locationName||"Aktueller Standort"}</span><b>${Math.round(state.weather.current.temperature_2m)} °C · Wetter</b>`;}
function renderWeatherPanel(){const e=$("#weatherPanel");if(!e)return;if(!state.weather){e.innerHTML="<p>Wetter wird beim Öffnen automatisch geladen.</p>";return;}let c=state.weather.current,d=state.weather.daily;e.innerHTML=`<div class="weatherDay"><h3>${state.locationName||"Standort"}</h3><b>${Math.round(c.temperature_2m)}°</b><p>Wind ${Math.round(c.wind_speed_10m||0)} km/h</p></div>`+d.time.map((day,i)=>`<div class="weatherDay"><h3>${new Date(day).toLocaleDateString("de-DE",{weekday:"short",day:"2-digit",month:"2-digit"})}</h3><b>${Math.round(d.temperature_2m_max[i])}°</b><p>min ${Math.round(d.temperature_2m_min[i])}° · Regen ${d.precipitation_probability_max[i]||0}%</p></div>`).join("");}
async function loadPois(){if(!state.coords)return;let{lat,lon}=state.coords;let radius=Number($("#radius").value||50000);if(radius>100000)radius=50000;let q=`[out:json][timeout:20];(node["amenity"="restaurant"](around:${radius},${lat},${lon});node["tourism"="camp_site"](around:${radius},${lat},${lon});node["tourism"="caravan_site"](around:${radius},${lat},${lon});node["tourism"="hotel"](around:${radius},${lat},${lon});node["tourism"="guest_house"](around:${radius},${lat},${lon}););out 45;`;let r=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",body:q});let j=await r.json();state.pois=(j.elements||[]).map(el=>{let t=el.tags||{},kind=t.amenity==="restaurant"?"restaurant":(t.tourism==="camp_site"||t.tourism==="caravan_site")?"camping":"hotel";return{id:"poi-"+el.id,name:t.name||kind,kind,lat:el.lat,lon:el.lon,img:kind==="restaurant"?DATA.imgs.food:kind==="camping"?DATA.imgs.camp:DATA.imgs.city,address:[t["addr:street"],t["addr:postcode"],t["addr:city"]].filter(Boolean).join(", "),tags:[kind]};});}
function initMap(){if(!window.L)return;if(!map){let s=state.coords||{lat:51.647,lon:7.096};map=L.map("map").setView([s.lat,s.lon],10);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);}renderMapMarkers();setTimeout(()=>map.invalidateSize(),120);}
function renderMapMarkers(){if(!map)return;markers.forEach(m=>m.remove());markers=[];[...DATA.suggestions,...state.pois].forEach(i=>{if(!i.lat||!i.lon)return;markers.push(L.marker([i.lat,i.lon]).addTo(map).bindPopup(`<b>${i.title||i.name}</b><br>${money(itemPrice(i))}`));});if(markers.length)try{map.fitBounds(L.featureGroup(markers).getBounds().pad(.2));}catch{}}

function renderBudget(){const e=$("#budgetList");if(e)e.innerHTML=chosen().map(i=>`<div class="listRow"><b>${i.title||i.name}</b><br>${money(itemPrice(i))}</div>`).join("")||"<p>Noch keine Kosten ausgewählt.</p>";}
function renderPack(){let filter=$("#packFilter")?.value||"Alle Kategorien",search=($("#packSearch")?.value||"").toLowerCase(),cats=[...new Set(DATA.pack.map(i=>i.cat))];if($("#packFilter")){$("#packFilter").innerHTML="<option>Alle Kategorien</option>"+cats.map(c=>`<option>${c}</option>`).join("");$("#packFilter").value=cats.includes(filter)?filter:"Alle Kategorien";}let items=DATA.pack;if(filter!=="Alle Kategorien")items=items.filter(i=>i.cat===filter);if(search)items=items.filter(i=>(i.name+" "+i.cat).toLowerCase().includes(search));let done=DATA.pack.filter(i=>state.packDone[i.id]).length;$("#packText").textContent=`${done} / ${DATA.pack.length}`;$("#packFill").style.width=(done/DATA.pack.length*100)+"%";$("#packCats").innerHTML=cats.map(c=>{let l=DATA.pack.filter(i=>i.cat===c),d=l.filter(i=>state.packDone[i.id]).length;return`<div class="packCat" data-pack-cat="${c}"><b>${c}</b><br><span>${d} / ${l.length}</span></div>`;}).join("");$("#products").innerHTML=items.map(i=>`<div class="packItem ${state.packDone[i.id]?"done":""}" data-pack="${i.id}"><img src="${i.icon}" alt=""><div><h3>${i.name}</h3><p>${i.cat} · Menge ${i.qty}</p></div><div class="check"></div></div>`).join("");$$("[data-pack]").forEach(r=>r.onclick=()=>{state.packDone[r.dataset.pack]=!state.packDone[r.dataset.pack];renderPack();});$$("[data-pack-cat]").forEach(c=>c.onclick=()=>{$("#packFilter").value=c.dataset.packCat;renderPack();});}
function renderPlan(){const e=$("#planList");if(e)e.innerHTML=chosen().map((i,n)=>`<div class="timelineItem"><b>Tag ${n+1}: ${i.title||i.name}</b><p>${i.desc||i.kind||""}</p></div>`).join("")||"<p>Noch nichts ausgewählt.</p>";}
function renderTimeline(){const e=$("#timeline");if(e)e.innerHTML=chosen().map((i,n)=>`<div class="timelineItem"><b>Tag ${n+1}</b><br>${i.title||i.name}</div>`).join("")||"<p>Noch keine Timeline vorhanden.</p>";}
function renderTours(){const e=$("#tourCards");if(e)e.innerHTML=DATA.suggestions.filter(i=>i.tags.includes("Radfahren")||i.tags.includes("Wandern")).map(i=>card(i)).join("");}
function renderHouse(){const e=$("#houseList");if(e)e.innerHTML=["Fenster schließen","Herd ausschalten","Wasserhahn prüfen","Müll entsorgen","Licht aus","Türen abschließen"].map(x=>`<label class="listRow"><input type="checkbox"> ${x}</label>`).join("");}
function exportText(){return["CREOVA Reiseplan","Budget: "+money(state.budget),"Kosten: "+money(totalCost()),"Standort: "+(state.locationName||"nicht gesetzt"),"","Auswahl:",...chosen().map(i=>"- "+(i.title||i.name)+" · "+money(itemPrice(i))),"","Offene Packliste:",...DATA.pack.filter(i=>!state.packDone[i.id]).map(i=>"- "+i.name)].join("\n");}
function renderExport(){if($("#exportText"))$("#exportText").value=exportText();}
function download(name,content,type){let b=new Blob([content],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href);}

function bind(){$$("[data-view]").forEach(b=>b.onclick=()=>nav(b.dataset.view));$("#budgetInput").oninput=e=>{state.budget=Number(e.target.value||0);render();};$("#persons").onchange=e=>{state.persons=Number(e.target.value||1);};$("#addInterest").onclick=()=>{let v=$("#customInterest").value.trim();if(v){state.interests.push(v);$("#customInterest").value="";render();}};$("#gpsBtn").onclick=useGps;$("#liveBtn").onclick=loadLiveData;$("#loadEverything").onclick=loadLiveData;$("#loadWeather").onclick=loadWeather;$("#refreshBtn").onclick=()=>{DATA.suggestions.reverse();render();toast("Vorschläge neu sortiert");};$("#clearBtn").onclick=()=>{state.selected=[];state.selectedPoi=[];state.budget=0;$("#budgetInput").value="";render();toast("Auswahl geleert");};$("#poiFilter").onchange=renderPois;$("#packSearch").oninput=renderPack;$("#packFilter").onchange=renderPack;$("#addPack").onclick=()=>{let v=$("#customPack").value.trim();if(v){DATA.pack.push({id:"custom-"+Date.now(),name:v,cat:"Eigene",icon:DATA.pack[0].icon,qty:"1 / 1"});$("#customPack").value="";renderPack();}};$("#resetBtn").onclick=()=>{location.href=location.pathname+"?v=9&reset="+Date.now();};$("#printBtn").onclick=()=>print();$("#printPlan").onclick=()=>print();$("#txtExport").onclick=()=>download("creova-reiseplan.txt",exportText(),"text/plain");$("#jsonExport").onclick=()=>download("creova-reiseplan.json",JSON.stringify(state,null,2),"application/json");$("#fitMap").onclick=renderMapMarkers;}
document.addEventListener("DOMContentLoaded",()=>{try{localStorage.clear();sessionStorage.clear();}catch{}bind();render();nav("ziel");if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=9").then(r=>r.update()).catch(()=>{});});
